name: plugin
description: A Flutter plugin for real-time pronunciation evaluation using Wav2Vec2 models.
version: 0.0.1
homepage: https://github.com/yourusername/pronunciation_evaluator

environment:
  sdk: ^3.7.2
  flutter: ">=3.3.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.example.pronunciation_evaluator
        pluginClass: PronunciationEvaluatorPlugin
      ios:
        pluginClass: SwiftPronunciationEvaluatorPlugin

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
